import { Subject, ContentItem, Profile, Plan, DashboardStats } from '@/types'

// ---------------------------------------------------------------------------
// Plans
// ---------------------------------------------------------------------------
export const MOCK_PLANS: Plan[] = [
  { id: 'plan-free', name: 'Free', price: 0, description: 'Default free access plan', is_active: true },
  { id: 'plan-basic', name: 'Basic', price: 499, description: 'Basic monthly plan', is_active: true },
  { id: 'plan-premium', name: 'Premium', price: 999, description: 'Premium monthly plan with all features', is_active: true },
]

// ---------------------------------------------------------------------------
// Profiles
// ---------------------------------------------------------------------------
export const MOCK_HEAD: Profile = {
  id: 'head-001',
  email: 'simi2suns@gmail.com',
  name: 'Head Admin',
  role: 'head',
  approval_status: 'approved',
  plan_id: null,
  payment_status: 'paid',
  avatar_url: null,
  created_at: '2025-01-01T00:00:00Z',
}

export const MOCK_TUTOR: Profile = {
  id: 'tutor-001',
  email: 'tutor@similearninghub.com',
  name: 'Simi Tutor',
  role: 'tutor',
  approval_status: 'approved',
  plan_id: null,
  payment_status: 'paid',
  avatar_url: null,
  created_at: '2025-01-01T00:00:00Z',
}

export const MOCK_PENDING_TUTOR: Profile = {
  id: 'tutor-002',
  email: 'applicant@similearninghub.com',
  name: 'Kavitha R',
  role: 'tutor',
  approval_status: 'pending',
  plan_id: null,
  payment_status: 'paid',
  avatar_url: null,
  created_at: '2025-08-15T00:00:00Z',
}

export const MOCK_MEMBER: Profile = {
  id: 'member-001',
  email: 'student@example.com',
  name: 'Arjun Kumar',
  role: 'member',
  approval_status: 'approved',
  plan_id: 'plan-free',
  plan: MOCK_PLANS[0],
  payment_status: 'paid',
  avatar_url: null,
  created_at: '2025-06-15T00:00:00Z',
}

export const MOCK_MEMBERS: Profile[] = [
  MOCK_MEMBER,
  {
    id: 'member-002',
    email: 'priya@example.com',
    name: 'Priya Sharma',
    role: 'member',
    approval_status: 'approved',
    plan_id: 'plan-basic',
    plan: MOCK_PLANS[1],
    payment_status: 'paid',
    avatar_url: null,
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'member-003',
    email: 'rahul@example.com',
    name: 'Rahul Mehta',
    role: 'member',
    approval_status: 'approved',
    plan_id: 'plan-free',
    plan: MOCK_PLANS[0],
    payment_status: 'unpaid',
    avatar_url: null,
    created_at: '2025-07-20T00:00:00Z',
  },
  {
    id: 'member-004',
    email: 'sneha@example.com',
    name: 'Sneha Reddy',
    role: 'member',
    approval_status: 'approved',
    plan_id: 'plan-premium',
    plan: MOCK_PLANS[2],
    payment_status: 'pending',
    avatar_url: null,
    created_at: '2025-08-01T00:00:00Z',
  },
  {
    id: 'member-005',
    email: 'amit@example.com',
    name: 'Amit Patel',
    role: 'member',
    approval_status: 'approved',
    plan_id: 'plan-basic',
    plan: MOCK_PLANS[1],
    payment_status: 'paid',
    avatar_url: null,
    created_at: '2025-08-10T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Subjects
// ---------------------------------------------------------------------------
export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'subj-math',
    name: 'Mathematics',
    slug: 'mathematics',
    description: 'Algebra, Calculus, Probability, and more',
    color_theme: '#6366f1',
    order_index: 0,
    created_by: 'tutor-001',
    created_at: '2025-01-15T00:00:00Z',
    content_count: 4,
    content_breakdown: { notes: 1, video: 1, youtube: 1, instagram: 1 },
  },
  {
    id: 'subj-physics',
    name: 'Physics',
    slug: 'physics',
    description: 'Mechanics, Optics, Thermodynamics, and Electromagnetism',
    color_theme: '#8b5cf6',
    order_index: 1,
    created_by: 'tutor-001',
    created_at: '2025-01-15T00:00:00Z',
    content_count: 4,
    content_breakdown: { notes: 2, video: 1, youtube: 1, instagram: 0 },
  },
  {
    id: 'subj-chemistry',
    name: 'Chemistry',
    slug: 'chemistry',
    description: 'Organic, Inorganic, and Physical Chemistry',
    color_theme: '#10b981',
    order_index: 2,
    created_by: 'tutor-001',
    created_at: '2025-02-01T00:00:00Z',
    content_count: 3,
    content_breakdown: { notes: 1, video: 0, youtube: 1, instagram: 1 },
  },
  {
    id: 'subj-biology',
    name: 'Biology',
    slug: 'biology',
    description: 'Cell Biology, Genetics, Ecology, and Human Physiology',
    color_theme: '#f59e0b',
    order_index: 3,
    created_by: 'tutor-001',
    created_at: '2025-02-15T00:00:00Z',
    content_count: 3,
    content_breakdown: { notes: 1, video: 1, youtube: 1, instagram: 0 },
  },
  {
    id: 'subj-cs',
    name: 'Computer Science',
    slug: 'computer-science',
    description: 'Data Structures, Algorithms, Python, and Web Development',
    color_theme: '#ef4444',
    order_index: 4,
    created_by: 'tutor-001',
    created_at: '2025-03-01T00:00:00Z',
    content_count: 4,
    content_breakdown: { notes: 1, video: 1, youtube: 1, instagram: 1 },
  },
]

// ---------------------------------------------------------------------------
// Content Items
// ---------------------------------------------------------------------------
export const MOCK_CONTENT: ContentItem[] = [
  // Mathematics
  {
    id: 'content-m1',
    subject_id: 'subj-math',
    type: 'notes',
    title: 'Differential Calculus — Complete Notes',
    description: 'Comprehensive notes covering limits, derivatives, and applications of differentiation.',
    file_url: '#',
    file_name: 'differential_calculus_notes.pdf',
    file_path: 'subj-math/content-m1/differential_calculus_notes.pdf',
    file_size: 2400000,
    external_url: null,
    is_published: true,
    is_pinned: true,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-01T10:00:00Z',
    updated_at: '2025-08-01T10:00:00Z',
  },
  {
    id: 'content-m2',
    subject_id: 'subj-math',
    type: 'video',
    title: 'Integration Techniques — Full Lecture',
    description: 'A 45-minute video lecture covering substitution, integration by parts, and partial fractions.',
    file_url: '#',
    file_name: 'integration_lecture.mp4',
    file_path: 'subj-math/content-m2/integration_lecture.mp4',
    file_size: 125000000,
    external_url: null,
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-05T14:00:00Z',
    updated_at: '2025-08-05T14:00:00Z',
  },
  {
    id: 'content-m3',
    subject_id: 'subj-math',
    type: 'youtube',
    title: 'Probability Made Easy — Visual Explanation',
    description: 'An excellent YouTube video explaining Bayes theorem with real-world examples.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.youtube.com/watch?v=HZGCoVF3YvM',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-10T09:00:00Z',
    updated_at: '2025-08-10T09:00:00Z',
  },
  {
    id: 'content-m4',
    subject_id: 'subj-math',
    type: 'instagram',
    title: 'Quick Tips — Trigonometry Identities',
    description: 'A quick reel covering the most important trig identities for exams.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.instagram.com/reel/CxYz12345/',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-12T16:00:00Z',
    updated_at: '2025-08-12T16:00:00Z',
  },

  // Physics
  {
    id: 'content-p1',
    subject_id: 'subj-physics',
    type: 'notes',
    title: 'Newton\'s Laws of Motion — Summary',
    description: 'Concise summary of all three laws with diagrams and solved examples.',
    file_url: '#',
    file_name: 'newtons_laws_summary.pdf',
    file_path: 'subj-physics/content-p1/newtons_laws_summary.pdf',
    file_size: 1800000,
    external_url: null,
    is_published: true,
    is_pinned: true,
    uploaded_by: 'tutor-001',
    created_at: '2025-07-20T08:00:00Z',
    updated_at: '2025-07-20T08:00:00Z',
  },
  {
    id: 'content-p2',
    subject_id: 'subj-physics',
    type: 'notes',
    title: 'Electromagnetism Formulas Sheet',
    description: 'All key formulas for electrostatics, magnetism, and electromagnetic induction.',
    file_url: '#',
    file_name: 'em_formulas.pdf',
    file_path: 'subj-physics/content-p2/em_formulas.pdf',
    file_size: 950000,
    external_url: null,
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-02T11:00:00Z',
    updated_at: '2025-08-02T11:00:00Z',
  },
  {
    id: 'content-p3',
    subject_id: 'subj-physics',
    type: 'video',
    title: 'Optics — Lens and Mirror Diagrams',
    description: 'Detailed walkthrough of ray diagrams for convex and concave mirrors and lenses.',
    file_url: '#',
    file_name: 'optics_lecture.mp4',
    file_path: 'subj-physics/content-p3/optics_lecture.mp4',
    file_size: 89000000,
    external_url: null,
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-08T15:00:00Z',
    updated_at: '2025-08-08T15:00:00Z',
  },
  {
    id: 'content-p4',
    subject_id: 'subj-physics',
    type: 'youtube',
    title: 'Thermodynamics — First and Second Law',
    description: 'Clear explanation of entropy, enthalpy, and the laws of thermodynamics.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-14T10:00:00Z',
    updated_at: '2025-08-14T10:00:00Z',
  },

  // Chemistry
  {
    id: 'content-c1',
    subject_id: 'subj-chemistry',
    type: 'notes',
    title: 'Organic Chemistry — Reaction Mechanisms',
    description: 'Step-by-step reaction mechanisms for SN1, SN2, E1, and E2 reactions.',
    file_url: '#',
    file_name: 'organic_mechanisms.pdf',
    file_path: 'subj-chemistry/content-c1/organic_mechanisms.pdf',
    file_size: 3200000,
    external_url: null,
    is_published: true,
    is_pinned: true,
    uploaded_by: 'tutor-001',
    created_at: '2025-07-25T09:00:00Z',
    updated_at: '2025-07-25T09:00:00Z',
  },
  {
    id: 'content-c2',
    subject_id: 'subj-chemistry',
    type: 'youtube',
    title: 'Periodic Table Trends Explained',
    description: 'Visual guide to electronegativity, ionization energy, and atomic radius trends.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://youtu.be/rz4Dd1I_fX0',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-06T12:00:00Z',
    updated_at: '2025-08-06T12:00:00Z',
  },
  {
    id: 'content-c3',
    subject_id: 'subj-chemistry',
    type: 'instagram',
    title: 'Balancing Equations — Quick Trick',
    description: 'A fun reel showing the fastest way to balance chemical equations.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.instagram.com/p/AbCdEfGhIjK/',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-11T17:00:00Z',
    updated_at: '2025-08-11T17:00:00Z',
  },

  // Biology
  {
    id: 'content-b1',
    subject_id: 'subj-biology',
    type: 'notes',
    title: 'Cell Structure and Organelles',
    description: 'Detailed notes with diagrams of animal and plant cell structures.',
    file_url: '#',
    file_name: 'cell_structure.pdf',
    file_path: 'subj-biology/content-b1/cell_structure.pdf',
    file_size: 4100000,
    external_url: null,
    is_published: true,
    is_pinned: true,
    uploaded_by: 'tutor-001',
    created_at: '2025-07-28T10:00:00Z',
    updated_at: '2025-07-28T10:00:00Z',
  },
  {
    id: 'content-b2',
    subject_id: 'subj-biology',
    type: 'video',
    title: 'DNA Replication — Step by Step',
    description: 'Animated explanation of the DNA replication process with Meselson-Stahl experiment.',
    file_url: '#',
    file_name: 'dna_replication.mp4',
    file_path: 'subj-biology/content-b2/dna_replication.mp4',
    file_size: 67000000,
    external_url: null,
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-03T13:00:00Z',
    updated_at: '2025-08-03T13:00:00Z',
  },
  {
    id: 'content-b3',
    subject_id: 'subj-biology',
    type: 'youtube',
    title: 'Genetics — Punnett Squares Made Easy',
    description: 'How to solve mono and dihybrid cross problems using Punnett squares.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.youtube.com/watch?v=pCDVRjquFOU',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-09T11:00:00Z',
    updated_at: '2025-08-09T11:00:00Z',
  },

  // Computer Science
  {
    id: 'content-cs1',
    subject_id: 'subj-cs',
    type: 'notes',
    title: 'Data Structures — Arrays, Stacks & Queues',
    description: 'Comprehensive notes with Python code examples for fundamental data structures.',
    file_url: '#',
    file_name: 'ds_arrays_stacks_queues.pdf',
    file_path: 'subj-cs/content-cs1/ds_arrays_stacks_queues.pdf',
    file_size: 2900000,
    external_url: null,
    is_published: true,
    is_pinned: true,
    uploaded_by: 'tutor-001',
    created_at: '2025-07-30T08:00:00Z',
    updated_at: '2025-07-30T08:00:00Z',
  },
  {
    id: 'content-cs2',
    subject_id: 'subj-cs',
    type: 'video',
    title: 'Binary Search — Implementation Walkthrough',
    description: 'Live coding session implementing binary search in Python with time complexity analysis.',
    file_url: '#',
    file_name: 'binary_search_walkthrough.mp4',
    file_path: 'subj-cs/content-cs2/binary_search_walkthrough.mp4',
    file_size: 54000000,
    external_url: null,
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-04T14:00:00Z',
    updated_at: '2025-08-04T14:00:00Z',
  },
  {
    id: 'content-cs3',
    subject_id: 'subj-cs',
    type: 'youtube',
    title: 'Web Development Roadmap 2025',
    description: 'A comprehensive guide to learning web development from scratch.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.youtube.com/watch?v=u72H_zZzkcw',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-07T10:00:00Z',
    updated_at: '2025-08-07T10:00:00Z',
  },
  {
    id: 'content-cs4',
    subject_id: 'subj-cs',
    type: 'instagram',
    title: 'Python Tips — List Comprehensions',
    description: 'Quick and fun reel explaining Python list comprehensions with examples.',
    file_url: null,
    file_name: null,
    file_path: null,
    file_size: null,
    external_url: 'https://www.instagram.com/reel/CzAbCdEfGhI/',
    is_published: true,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-13T18:00:00Z',
    updated_at: '2025-08-13T18:00:00Z',
  },

  // Draft content (tutor-only visible)
  {
    id: 'content-draft1',
    subject_id: 'subj-math',
    type: 'notes',
    title: '[DRAFT] Linear Algebra — Matrices Intro',
    description: 'Work in progress notes on matrix operations and determinants.',
    file_url: '#',
    file_name: 'linear_algebra_draft.pdf',
    file_path: 'subj-math/content-draft1/linear_algebra_draft.pdf',
    file_size: 1500000,
    external_url: null,
    is_published: false,
    is_pinned: false,
    uploaded_by: 'tutor-001',
    created_at: '2025-08-15T20:00:00Z',
    updated_at: '2025-08-15T20:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Dashboard Stats
// ---------------------------------------------------------------------------
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_members: MOCK_MEMBERS.length,
  active_subjects: MOCK_SUBJECTS.length,
  total_lessons: MOCK_CONTENT.filter(c => c.is_published).length,
  storage_used_bytes: MOCK_CONTENT.reduce((sum, c) => sum + (c.file_size ?? 0), 0),
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Check if the app is running in demo mode */
export function isDemoMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const isPlaceholder = !url || url.includes('your_supabase') || url.includes('placeholder')
  if (process.env.NEXT_PUBLIC_DEMO_MODE === 'false' && !isPlaceholder) {
    return false
  }
  // Default to true on Vercel / local if demo mode is not explicitly disabled with real keys
  return true
}

/** Get mock content filtered by subject slug */
export function getMockContentBySubject(slug: string): ContentItem[] {
  const subject = MOCK_SUBJECTS.find(s => s.slug === slug)
  if (!subject) return []
  return MOCK_CONTENT.filter(c => c.subject_id === subject.id && c.is_published)
}

/** Get mock subject by slug */
export function getMockSubjectBySlug(slug: string): Subject | undefined {
  return MOCK_SUBJECTS.find(s => s.slug === slug)
}
